///////////////////////////////////////////////////////////
//  Aletrtas.cs
//  Implementation of the Class Aletrtas
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 1:35:15
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Diagrama_Clases {
	public class Aletrtas {

		private string estado_Actual;
		private DateTime fecha_Emision;
		private int id_Alerta;
		private string mensaje;
		private string nivel_Urgencia;
		private string tipo_Alarma;

		public Aletrtas(){

		}
		public void nuevo()
		{

		}


		~Aletrtas(){

		}

	}//end Aletrtas

}//end namespace Diagrama_Clases