///////////////////////////////////////////////////////////
//  Deteccion_Plaga .cs
//  Implementation of the Class Deteccion_Plaga 
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 1:35:15
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Diagrama_Clases
{
    public class Deteccion_Plaga
    {
        public int Id { get; set; }
        public string plaga { get; set; }
        public DateTime fecha_Deteccion { get; set; }
        public string ubicacion { get; set; }
        public string observacion { get; set; }
    }
}