///////////////////////////////////////////////////////////
//  Incidencia .cs
//  Implementation of the Class Incidencia 
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 10:25:59
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Diagrama_Clases;
namespace Diagrama_Clases {
	public class Incidencia  {

		public string descipcion;
		public string estado;
		public DateTime fecha_Detecion;
		private int id_Incidencia;
		public string nivel_Severidad;
		private int nuevo;
		public Diagrama_Clases.Aletrtas m_Aletrtas;
		public Diagrama_Clases.Recomendaciones m_Recomendaciones;
		private int nuevo1;

		public Incidencia (){

		}

		~Incidencia (){

		}

	}//end Incidencia 

}//end namespace Diagrama_Clases