///////////////////////////////////////////////////////////
//  Labor_agricola.cs
//  Implementation of the Class Labor_agricola
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 1:35:15
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Diagrama_Clases;
namespace Diagrama_Clases {
	public class Labor_agricola : Labor_Fitosanitario, Labor_Polinizacion {

		private int duracion_Horas;
		public DateTime fecha_Laboracion;
		private int id_Labor;
		public string observaciones;
		public Deteccion_Plaga  m_Deteccion_Plaga ;
		public Diagrama_Clases.Lote m_Lote;

		public Labor_agricola(){

		}

		~Labor_agricola(){

		}

	}//end Labor_agricola

}//end namespace Diagrama_Clases