///////////////////////////////////////////////////////////
//  Labor_Polinizacion.cs
//  Implementation of the Class Labor_Polinizacion
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 1:35:15
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Diagrama_Clases {
	public class Labor_Polinizacion {

		private int id_Labor_Polinizacion;
		private string labor_Polinizacion;
		private double porcentaje_Cobertura;
		private string tecnica_Polinizacion;

		public Labor_Polinizacion(){

		}

		~Labor_Polinizacion(){

		}

	}//end Labor_Polinizacion

}//end namespace Diagrama_Clases