///////////////////////////////////////////////////////////
//  Labor_Fitosanitario.cs
//  Implementation of the Class Labor_Fitosanitario
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 1:35:15
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Diagrama_Clases;
namespace Diagrama_Clases {
	public class Labor_Fitosanitario {

		private double dosis_Litros;
		private DateTime fecha_Aplicacion;
		private int id_Sanidad;
		private string producto_Aplicado;

		public Labor_Fitosanitario(){

		}

		~Labor_Fitosanitario(){

		}

	}//end Labor_Fitosanitario

}//end namespace Diagrama_Clases