///////////////////////////////////////////////////////////
//  Lote.cs
//  Implementation of the Class Lote
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 1:35:15
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Diagrama_Clases;
namespace Diagrama_Clases {
	public class Lote {

		private double are_Superficie;
		private string estado_Actual;
		private int id_Lote;
		public Diagrama_Clases.Plantación m_Plantación;

		public Lote(){

		}

		~Lote(){

		}

	}//end Lote

}//end namespace Diagrama_Clases