///////////////////////////////////////////////////////////
//  Plantación.cs
//  Implementation of the Class Plantación
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 1:35:15
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Diagrama_Clases {
	public class Plantación {

		private DateTime area_Hectarea;
		private int fecha_Siembra;
		private int id_Plantacion;
		private string nombre_Plantacion;
		public string nuevo;
		private string ubicacion_Plantacion;

		public Plantación(){

		}

		~Plantación(){

		}

	}//end Plantación

}//end namespace Diagrama_Clases