///////////////////////////////////////////////////////////
//  Recomendaciones.cs
//  Implementation of the Class Recomendaciones
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 1:35:15
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Diagrama_Clases {
	public class Recomendaciones {

		private double dosis_Sugerida;
		private DateTime fecha_Sugerida;
		private int id_Recomendaciones;
		private string tratamiento_Sugerido;

		public Recomendaciones(){

		}

		~Recomendaciones(){

		}

	}//end Recomendaciones

}//end namespace Diagrama_Clases