///////////////////////////////////////////////////////////
//  Trabajador.cs
//  Implementation of the Class Trabajador
//  Generated by Enterprise Architect
//  Created on:      18-jul-2026 1:35:15
//  Original author: USER
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Diagrama_Clases;
namespace Diagrama_Clases {
	public class Trabajador {

		public string cedula_Trabajdor;
		private int id_Trabajador;
		public string nombre_Trabajador;
		public string rol_Cargo;
		public string teléfono;
		public Diagrama_Clases.Labor_agricola m_Labor_agricola;

		public Trabajador(){

		}

		~Trabajador(){

		}

	}//end Trabajador

}//end namespace Diagrama_Clases